name: Build and Release flutter based webapp
on: push
jobs:
    sonarcloud:
     name: SonarCloud
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    hosting:
      name: FLutter web app build
      needs: sonarcloud
      runs-on: ubuntu-latest
      steps:
        # Checkout Repository
        - uses: actions/checkout@v1

        # Install Flutter 
        - uses: subosito/flutter-action@v1
          with:
            channel: 'dev'

        # Build flutter Web App 
        - name: Build Website
          run: |
            flutter config --enable-web
            flutter build web

    
    deploy:
        name: Deploy
        needs: hosting
        runs-on: ubuntu-latest
        steps:
         - name: Checkout Repo
           uses: actions/checkout@master
         - name: Deploy to Firebase
           uses: w9jds/firebase-action@master
           with:
              args: deploy --only hosting:production-weapp
           env:
              FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
   
    container:
       name: Ghcr docker Image build
       needs: hosting
       runs-on: ubuntu-latest
       steps:
         - name: Checkout Repo
           uses: actions/checkout@master
       
         - name: creating container env
           uses: docker/setup-buildx-action@v1
         - name: docker login 
           uses: docker/login-action@v1
           env:
              GIT_USER: ${{ github.actor}}
              GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           with:
            registry: ghcr.io
            username: $env.GIT_USER
            password: ${{ env.GIT_TOKEN }}
         - name: build & publish docker image
           uses: docker/build-push-action@v2
           env: 
              REGISTRY: ghcr.io
           with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ env.REGISTRY }}/${{ github.repository }}/flutter:1
        
         - name: listing images
           run: 
             docker images
    
